export const comments = [
  {
    createdAt: '2022-11-08T23:32:51.233Z',
    content:
      'Voluptas ex laborum ut. Numquam aut ab reiciendis consequatur molestiae veritatis ratione ex. Maiores adipisci ab illum minima dolores.',
    author: 'Bill Weber',
    avatar: 'http://loremflickr.com/640/480/food',
    thumbsUp: 104,
    thumbsDown: 48,
    id: '1',
  },
  {
    createdAt: '2022-11-09T14:18:57.058Z',
    content:
      'Quam voluptatem expedita quasi placeat iusto nisi est aliquam deserunt. Id enim et aut optio. Totam quia adipisci quisquam vero aut asperiores hic. Vel libero expedita dignissimos dolore.',
    author: 'Joyce Marks V',
    avatar: 'http://loremflickr.com/640/480/animals',
    thumbsUp: 27,
    thumbsDown: 72,
    id: '2',
  },
  {
    createdAt: '2022-11-09T04:39:34.462Z',
    content:
      'Ex ut quisquam. Commodi rerum qui nihil illo et qui porro dolor. Possimus error eos nam modi dicta. Occaecati voluptatem amet dolorem dolore quis debitis accusantium provident nostrum. Rerum non qui voluptates sapiente quas ipsam aut at.',
    author: 'Ernest Lehner',
    avatar: 'http://loremflickr.com/640/480/sports',
    thumbsUp: 18,
    thumbsDown: 64,
    id: '3',
  },
  {
    createdAt: '2022-11-08T20:31:42.329Z',
    content:
      'Nemo ut eius dolores dolores non. Perspiciatis facere quaerat commodi inventore facilis. Consequatur aperiam maiores amet. Modi libero ducimus architecto vero. Est ab sit illum et dolorem ut.',
    author: 'Connie Huels',
    avatar: 'http://loremflickr.com/640/480/city',
    thumbsUp: 97,
    thumbsDown: 45,
    id: '4',
  },
  {
    createdAt: '2022-11-09T11:04:58.878Z',
    content: 'Saepe expedita repel',
    author: 'Germane Lynch',
    avatar: 'http://loremflickr.com/640/480/people',
    thumbsUp: 10,
    thumbsDown: 16,
    id: '5',
  },
  {
    createdAt: '2022-11-08T22:34:50.646Z',
    content: 'Culpa non ut labore ',
    author: 'Mari Montgomery',
    avatar: 'http://loremflickr.com/640/480/animals',
    thumbsUp: 2,
    thumbsDown: 38,
    id: '6',
  },
  {
    createdAt: '2022-11-09T23:20:01.930Z',
    content: 'Aliquam sit quis ver',
    author: 'Bianca Vinson',
    avatar: 'http://loremflickr.com/640/480/transport',
    thumbsUp: 71,
    thumbsDown: 6,
    id: '7',
  },
  {
    createdAt: '2022-11-10T08:56:19.501Z',
    content: 'Cillum qui exercitat',
    author: 'Imelda Sweet',
    avatar: 'http://loremflickr.com/640/480/fashion',
    thumbsUp: 44,
    thumbsDown: 65,
    id: '8',
  },
  {
    createdAt: '2022-11-09T18:56:22.673Z',
    content: 'Reprehenderit nisi s',
    author: 'Jorden Warren',
    avatar: 'http://loremflickr.com/640/480/people',
    thumbsUp: 82,
    thumbsDown: 80,
    id: '9',
  },
  {
    createdAt: '2022-11-10T06:49:35.956Z',
    content: '',
    author: '',
    avatar: 'http://loremflickr.com/640/480/people',
    thumbsUp: 47,
    thumbsDown: 42,
    id: '10',
  },
];
